src/Entity/ExpenseEntry.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExpenseEntryRepository")
 */
class ExpenseEntry
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $value;

    /**
     * @ORM\Column(type="date")
     */
    private $expense_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expense_entry;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Expense", inversedBy="expenseEntries")
     */
    private $expense;

    /**
     * @return mixed
     */
    public function getExpense()
    {
        return $this->expense;
    }

    /**
     * @param mixed $expense
     */
    public function setExpense($expense): void
    {
        $this->expense = $expense;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getExpenseDate(): ?\DateTimeInterface
    {
        return $this->expense_date;
    }

    public function setExpenseDate(\DateTimeInterface $expense_date): self
    {
        $this->expense_date = $expense_date;

        return $this;
    }

    public function getExpenseEntry(): ?\DateTimeInterface
    {
        return $this->expense_entry;
    }

    public function setExpenseEntry(\DateTimeInterface $expense_entry): self
    {
        $this->expense_entry = $expense_entry;

        return $this;
    }
}

src/Form/ExpenseEntryType.php
<?php

namespace App\Form;

use App\Entity\ExpenseEntry;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExpenseEntryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('value')
            ->add('expense_date')
            //->add('expense_entry')
            ->add('expense')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ExpenseEntry::class,
        ]);
    }
}

src/Controller/ExpenseEntryController.php
<?php

namespace App\Controller;

use App\Entity\ExpenseEntry;
use App\Form\ExpenseEntryType;
use App\Repository\ExpenseEntryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/expense/entry")
 */
class ExpenseEntryController extends AbstractController
{
    /**
     * @Route("/", name="expense_entry_index", methods="GET")
     */
    public function index(ExpenseEntryRepository $expenseEntryRepository): Response
    {
        return $this->render('expense_entry/index.html.twig', ['expense_entries' => $expenseEntryRepository->findAll()]);
    }

    /**
     * @Route("/new", name="expense_entry_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $expenseEntry = new ExpenseEntry();
        $now = new \DateTime();
        $expenseEntry->setExpenseEntry($now);
        $form = $this->createForm(ExpenseEntryType::class, $expenseEntry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($expenseEntry);
            $em->flush();

            return $this->redirectToRoute('expense_entry_index');
        }

        return $this->render('expense_entry/new.html.twig', [
            'expense_entry' => $expenseEntry,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="expense_entry_show", methods="GET")
     */
    public function show(ExpenseEntry $expenseEntry): Response
    {
        return $this->render('expense_entry/show.html.twig', ['expense_entry' => $expenseEntry]);
    }

    /**
     * @Route("/{id}/edit", name="expense_entry_edit", methods="GET|POST")
     */
    public function edit(Request $request, ExpenseEntry $expenseEntry): Response
    {
        $form = $this->createForm(ExpenseEntryType::class, $expenseEntry);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('expense_entry_edit', ['id' => $expenseEntry->getId()]);
        }

        return $this->render('expense_entry/edit.html.twig', [
            'expense_entry' => $expenseEntry,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="expense_entry_delete", methods="DELETE")
     */
    public function delete(Request $request, ExpenseEntry $expenseEntry): Response
    {
        if ($this->isCsrfTokenValid('delete'.$expenseEntry->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($expenseEntry);
            $em->flush();
        }

        return $this->redirectToRoute('expense_entry_index');
    }
}

templates/expense_entry/_delete_form.html.twig
<form method="post" action="{{ path('expense_entry_delete', {'id': expense_entry.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ expense_entry.id) }}">
    <button class="btn">Delete</button>
</form>

templates/expense_entry/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/expense_entry/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ExpenseEntry{% endblock %}

{% block body %}
    <h1>Edit ExpenseEntry</h1>

    {{ include('expense_entry/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('expense_entry_index') }}">back to list</a>

    {{ include('expense_entry/_delete_form.html.twig') }}
{% endblock %}

templates/expense_entry/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ExpenseEntry index{% endblock %}

{% block body %}
    <h1>ExpenseEntry index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Value</th>
                <th>Expense_date</th>
                <th>Expense_entry</th>
                <th>Expense</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for expense_entry in expense_entries %}
            <tr>
                <td>{{ expense_entry.value }}</td>
                <td>{{ expense_entry.expenseDate ? expense_entry.expenseDate|date('Y-m-d') : '' }}</td>
                <td>{{ expense_entry.expenseEntry ? expense_entry.expenseEntry|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ expense_entry.expense }}</td>
                <td>
                    <a href="{{ path('expense_entry_show', {'id': expense_entry.id}) }}">show</a>
                    <a href="{{ path('expense_entry_edit', {'id': expense_entry.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('expense_entry_new') }}">Create new</a>
{% endblock %}

templates/expense_entry/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ExpenseEntry{% endblock %}

{% block body %}
    <h1>Create new ExpenseEntry</h1>

    {{ include('expense_entry/_form.html.twig') }}

    <a href="{{ path('expense_entry_index') }}">back to list</a>
{% endblock %}

templates/expense_entry/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ExpenseEntry{% endblock %}

{% block body %}
    <h1>ExpenseEntry</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ expense_entry.id }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ expense_entry.value }}</td>
            </tr>
            <tr>
                <th>Expense</th>
                <td>{{ expense_entry.expense }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ expense_entry.expense.category }}</td>
            </tr>
            <tr>
                <th>Group</th>
                <td>{{ expense_entry.expense.expensegroup }}</td>
            </tr>
            <tr>
                <th>Expense_date</th>
                <td>{{ expense_entry.expenseDate ? expense_entry.expenseDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Expense_entry</th>
                <td>{{ expense_entry.expenseEntry ? expense_entry.expenseEntry|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('expense_entry_index') }}">back to list</a>

    <a href="{{ path('expense_entry_edit', {'id': expense_entry.id}) }}">edit</a>

    {{ include('expense_entry/_delete_form.html.twig') }}
{% endblock %}